name: Validate Conventional Commits
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  hqprs:
    runs-on: ubuntu-latest
    steps:
      - name: conventional-pr
        uses: Namchee/conventional-pr@v0.5.0
        with:
          access_token: YOUR_GITHUB_ACCESS_TOKEN_HERE
